version: '3.8'

services:
  frontend:
    container_name: frontend
    # image: ghcr.io/szimina/yurv2/frontend:latest
    build: .
    ports:
      - 80:80


  # nginx:
  #   image: nginx
  #   ports:
  #     - 80:80
  #   restart: always
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - frontend_dist:/var/www/frontend:ro
  #     # - ./certbot/www/:/var/www/certbot/:ro
  #     # - ./certbot/conf/:/etc/letsencrypt/:ro

  # certbot:
  #   image: certbot/certbot:latest
  #   networks:
  #     - webnet
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw

# networks:
#   webnet:

# volumes:
#   frontend_dist: