services:
  frontend:
    image: ghcr.io/szimina/yurv2/frontend:latest
    networks:
      - webnet
    volumes:
      - frontend_dist:/app/dist

  nginx:
    image: nginx:alpine
    depends_on:
      - frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:ro
      - frontend_dist:/var/www/frontend:ro
    networks:
      - webnet
    restart: unless-stopped

  certbot:
    image: certbot/certbot:latest
    networks:
      - webnet
    volumes:
      - ./certbot/www:/var/www/certbot:rw  
      - ./certbot/conf:/etc/letsencrypt:rw
    profiles: ["certbot"]
    deploy:
      replicas: 0

volumes:
  frontend_dist:

networks:
  webnet: